services:
  firewatcher:
    image: firewatcher:local
    container_name: firewatcher
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ${IMG_FOLDER_PATH}:/data/fire_watcher/img
    environment:
      TZ: UTC
    env_file:
      - .env
